name : ewscli
cmdname : ewscli
summary : EWS (Exchange Web Service) CLI
description : EWS (Exchange Web Service) CLI
version : 0.0.5
changelog : Update to 0.0.5
url : https://github.com/greymd/ewscli
author: Yasuhiro Yamada
email : yamadagrep@gmail.com
libdir : /usr/lib
